#ifndef CONTROLS_H_INCLUDED
#define CONTROLS_H_INCLUDED

#define CONTROLS 256
extern char controls[CONTROLS];

#define CONTROL_DISABLE_LFO_AM 0
#define CONTROL_DISABLE_LFO_FM 1
#define CONTROL_DISABLE_FEEDBACK 2
#define CONTROL_DISABLE_DAC 3
#define CONTROL_DISABLE_DETUNE 4
#define CONTROL_DISABLE_SPECIAL 5
#define CONTROL_DISABLE_SSG 6
#define CONTROL_DISABLE_CSM 7
#define CONTROL_DISABLE_LEVEL 8
#define CONTROL_DISABLE_RATE 9
#define CONTROL_DISABLE_FREQUENCY 10
#define CONTROL_DISABLE_VGM_YM2612 11

#endif
