#ifndef CONTROLS_H_INCLUDED
#define CONTROLS_H_INCLUDED

#define CONTROLS 256
extern char controls[CONTROLS];

#define CONTROL_DISABLE_LFO_AM 0
#define CONTROL_DISABLE_LFO_FM 1
#define CONTROL_DISABLE_FEEDBACK 2
#define CONTROL_DISABLE_DAC 3
#define CONTROL_DISABLE_DETUNE 4
#define CONTROL_DISABLE_SPECIAL 5
#define CONTROL_DISABLE_SSG 6
#define CONTROL_DISABLE_CSM 7
#define CONTROL_DISABLE_LEVEL 8
#define CONTROL_DISABLE_RATE 9

#define CONTROL_DISABLE_FREQUENCY 10

#define CONTROL_DISABLE_VGM_YM2612 20
#define CONTROL_ENABLE_LOGGING 21

#define CONTROL_DISABLE_CH1 30
#define CONTROL_DISABLE_CH2 31
#define CONTROL_DISABLE_CH3 32
#define CONTROL_DISABLE_CH4 33
#define CONTROL_DISABLE_CH5 34
#define CONTROL_DISABLE_CH6 35

#endif
